<?php

class IntegrationTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		//\DB::table('integration')->delete();
        
		\DB::table('integration')->insert(array (
			0 => 
			array (
				'id' => 1,
				'name' => '<i class="fa fa-vk"></i> Вконтакте',
				'keyword' => 'vk',
				'short_description' => 'Посты посетителей на стене вашей группы или комментарии к вашим постам отображаются в Usedesk как запросы.',
				'type' => 'free',
				'month_price' => 0,
				'year_price' => 0,
				'long_description' => '',
				'icon' => NULL,
				'default_status' => 1,
				'status' => 1,
			),
			1 => 
			array (
				'id' => 2,
				'name' => '<i class="entypo-twitter"></i> Twitter',
				'keyword' => 'twitter',
			'short_description' => 'Отвечайте на публичные твиты с упоминанием вашей страницы и личные сообщения из Usedesk. Об ограничении в 140 знаков мы не забыли :)',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 1,
			'status' => 1,
		),
		2 => 
		array (
			'id' => 3,
			'name' => '<i class="entypo-facebook-squared"></i> Facebook',
			'keyword' => 'fb',
			'short_description' => 'Публикации посетителей и сообщения вашей страницы превращаются в запросы в Usedesk.',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 1,
			'status' => 1,
		),
		3 => 
		array (
			'id' => 4,
			'name' => '<i class="entypo-chat"></i> JivoSite',
			'keyword' => 'jivo',
			'short_description' => 'Общайтесь с клиентами на сайте с помощью онлайн консультанта JivoSite. Диалоги в чате и оффлайн сообщения сохраняются в UseDesk в историю клиента. Если клиент обратится повторно по почте или телефону, не нужно открывать JivoSite. Все детали предыдущего общения уже на виду в UseDesk.',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 0,
		),
		4 => 
		array (
			'id' => 5,
			'name' => '<i class="entypo-eye"></i> Мониторинг',
			'keyword' => 'monitor',
			'short_description' => 'Задайте ключевые слова, и Usedesk найдет комментарии и посты с ними в Контакте, Фейсбуке и Твиттере. <a href="https://usedesk.ru/monitoring.html?utm_source=integrations-page" target="_blank">Подробнее</a>.',
			'type' => 'paid',
			'month_price' => 5900,
			'year_price' => 60000,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 0,
		),
		5 => 
		array (
			'id' => 6,
			'name' => '<i class="entypo-users"></i> Поиск профилей в социальных сетях',
			'keyword' => 'fullcontact',
			'short_description' => 'Штука, которая сама находит и показывает профили клиентов в соцсетях',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 0,
		),
		6 => 
		array (
			'id' => 7,
			'name' => '<i class="entypo-shareable"></i>Usedesk  API',
			'keyword' => 'api',
			'short_description' => 'Документация доступна на <a href="https://api.usedesk.ru/" target="_blank">api.usedesk.ru</a>',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		7 => 
		array (
			'id' => 8,
			'name' => '<i class="entypo-help-circled"></i> Центр поддержки',
			'keyword' => 'support',
			'short_description' => ' Большинство клиентов предпочитают находить ответы самостоятельно, прежде чем обратиться в службу поддержки. Предоставьте им такую возможность с Центром поддержки от Usedesk.',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 1,
			'status' => 1,
		),
		8 => 
		array (
			'id' => 9,
			'name' => '<i class="entypo-heart"></i> Модуль CSI',
			'keyword' => 'nps',
			'short_description' => 'Запрос уровня удовлетворенности клиента ответами поддержки',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 1,
			'status' => 1,
		),
		9 => 
		array (
			'id' => 10,
			'name' => '<i class="entypo-clock"></i> Рабочее время в отчетах',
			'keyword' => 'work_time',
			'short_description' => 'Включайте интеграцию и настраивайте <a href="https://secure.usedesk.ru/settings/working-days">рабочее время в Настройки > Время работы офиса</a>, если ваша команда работает не 24/7',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		10 => 
		array (
			'id' => 11,
			'name' => '<i class="entypo-back-in-time"></i> SLA',
			'keyword' => 'sla',
			'short_description' => 'Гарантируйте клиентам быстрое решение проблем с помощью соглашения об уровне обслуживания',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		11 => 
		array (
			'id' => 13,
			'name' => '<i class="entypo-laptop"></i> DialTech',
			'keyword' => 'ai',
			'short_description' => 'Умный робот DialTech помогает агентам поддержки отвечать на вопросы клиентов',
			'type' => 'paid',
			'month_price' => 100500,
			'year_price' => 100500,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		12 => 
		array (
			'id' => 14,
			'name' => '<i class="entypo-phone"></i> Телефония',
			'keyword' => 'telephony',
			'short_description' => 'Звонки превращаются в запросы в UseDesk. Внутри запроса — ссылка на запись разговора. Теперь ни одно обращение не пропущено!',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		13 => 
		array (
			'id' => 15,
			'name' => '<i class="fa fa-asterisk"></i> Zapier',
			'keyword' => 'zapier',
			'short_description' => 'Соедините UseDesk с +750 сервисами через Zapier без программирования',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		14 => 
		array (
			'id' => 16,
			'name' => '<i class="entypo-doc-landscape"></i> Дополнительные поля',
			'keyword' => 'additional_fields',
			'short_description' => 'Создавайте индивидуальные поля, чтобы подробнее описать запрос и добавлять категорию в удобном формате.',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		15 => 
		array (
			'id' => 17,
			'name' => '<i class="fa fa-comments"></i> Whats Help',
			'keyword' => 'whatshelp',
			'short_description' => 'Чат Whats Help объединяет мессенджеры Телеграм, Вайбер, Вконтакте и Фейсбук. Объедините свой аккаунт Whats Help с UseDesk, чтобы видеть всю историю переписки в мессенджерах в запросах.',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		16 => 
		array (
			'id' => 19,
			'name' => '<i class="entypo-star"></i> Главред',
			'keyword' => 'glavred',
			'short_description' => 'Главред помогает очистить шаблоны ответов от словесного мусора, проверяет на соответствие информационному стилю. ',
			'type' => 'free',
			'month_price' => 0,
			'year_price' => 0,
			'long_description' => '',
			'icon' => NULL,
			'default_status' => 0,
			'status' => 1,
		),
		17 => 
		array (
			'id' => 21,
			'name' => '<i class="entypo-graduation-cap"></i> Проверка орфографии',
			'keyword' => 'speller',
		'short_description' => 'Пусть ваша служба поддержки славится грамотностью :) Яндекс.Спеллер помогает находить и исправлять орфографические ошибки в русском, украинском или английском тексте. ',
		'type' => 'free',
		'month_price' => 0,
		'year_price' => 0,
		'long_description' => '',
		'icon' => NULL,
		'default_status' => 0,
		'status' => 1,
	),
	18 => 
	array (
		'id' => 23,
		'name' => '<i class="entypo-chat"></i> Online Chat',
		'keyword' => 'chat',
		'short_description' => 'Функционал вебчата',
		'type' => 'paid',
		'month_price' => 100500,
		'year_price' => 100500,
		'long_description' => '',
		'icon' => NULL,
		'default_status' => 0,
		'status' => 1,
	),
	19 => 
	array (
		'id' => 25,
		'name' => '<i class="entypo-chat"></i> Кобраузинг',
		'keyword' => 'cobrowsing',
		'short_description' => '',
		'type' => 'paid',
		'month_price' => 1000,
		'year_price' => 12000,
		'long_description' => '',
		'icon' => NULL,
		'default_status' => 0,
		'status' => 1,
	),
	20 => 
	array (
		'id' => 26,
		'name' => '<i class="entypo-chat"></i> Мессенджеры',
		'keyword' => 'messenger',
		'short_description' => '',
		'type' => 'paid',
		'month_price' => NULL,
		'year_price' => NULL,
		'long_description' => '',
		'icon' => NULL,
		'default_status' => 0,
		'status' => 1,
	),
	21 => 
	array (
		'id' => 28,
		'name' => '<i class="entypo-chat"></i> RetailCRM',
		'keyword' => 'retail_crm',
		'short_description' => '',
		'type' => 'paid',
		'month_price' => NULL,
		'year_price' => NULL,
		'long_description' => '',
		'icon' => NULL,
		'default_status' => 0,
		'status' => 1,
	),
));
	}

}
